### ISSUE TITLE
Which template format is better to use in alpha version.

### ISSUE THREAD

**Issue by marcinsydor** [dart-bridge/framework#14]
I've been playing with the templates on server side now. Which format is more stable. Bridge html or Handlebars? 
Could you also give me quick example how to add template partials to Bridge template?

**Comment by emilniklas** [comment]
Bridge templates is the most stable. The other formats use it too, by the way, but after it has been processed. That's why should should be able to have variables in Markdown for example.

```
@include ('some.template')
```

The contents of the parenthesis can be any expression:

```
@include ('partial.$partial')
```

**Comment by marcinsydor** [comment]
Thanks, it works well so far.
I only found a small bug. If code is formatted as bellow example:

```
<body>
@include ('partials.header')
```

Then I'm getting an error:

```
in ShutdownIsolate: 'file:///Users/user/Repos/lab/bridge/.templates.dart': error: line 189 pos 20: ':' expected
${await {{ include }}('partials.header')}
                   ^
```

It's fine if I add space chars before `@include` 

```
<body>
    @include ('partials.header')
```

**Comment by emilniklas** [comment]
Hmm. It's the handlebars translation that's acting up... I'll have tto really think that one through..

**Comment by emilniklas** [comment]
As of `1.0.0-alpha3`:
- `asHandlebars` on `Template` is removed entirely
- Partials work for both Handlebars and Jade
- Extends are added and is supported in Jade (documentation is coming)
