### ISSUE TITLE
Ignore commented variables in templates.

### ISSUE THREAD

**Issue by marcinsydor** [dart-bridge/framework#15]
I don't know if that's a bug but if I comment something in template e.g. `<!--<p>$key</p>-->` the variable in the line is still executed. Should not the compiler ignore that variable?.

**Comment by emilniklas** [comment]
You can use double slash to comment out a line:

```
<h1>Visible</h1>
// Never visible.   $var <– never evaluated
<p>Visible</p>
```

**Comment by marcinsydor** [comment]
Thanks
