### ISSUE TITLE
Advice on deploying website to live server. 

### ISSUE THREAD

**Issue by marcinsydor** [dart-bridge/framework#17]
I'm really happy how the framework works for far. Now I would like to deploy a website somewhere to live server. Then test it and show it to my client at some point. 
I know now that I could use docker container for it e.g. on digitalocean.com or on Google App Engine. I've been playing with it a bit but It's not very straightforward for me. 
I've also checked your post: http://emilpersson.se/dart-service-with-upstart-in-ubuntu . I have an account on TSOHost.com. It's could linux hosting server. I'm wondering if that would be possible to setup my website there. 
I would appreciate your advice and thoughts on this.

**Comment by emilniklas** [comment]
Any option with Dart support will work. I'd be very surprised if TSOHost has that without buying a VPS, though.

In any case. At some point you will have to specify a dart command that starts the server up. This is it:

``` dart
dart bridge start --production
```

This will log the console into a file called `cupid.log` instead of into a terminal that you can't see.

If you're not able to specify the entire command, only a dart file to start, do this:
- Create a new file in the root of your project called `server.dart`
- Put this in it:

``` dart
import 'bridge' as bridge;
main() {
  bridge.main(['start', '--production']);
}
```
- Then reference that `server.dart` file in the startup dart file

**Comment by marcinsydor** [comment]
Thanks. I've decided to use docker to deploy the website. I've chosen `google/dart-runtime` as base image. https://registry.hub.docker.com/u/google/dart-runtime/
As you advised I've created `server.dart` but put it in `bin` folder. And I've amended import to `import '../bridge' as bridge;` and port to `8080`. To test I run `server.dart` and the website started up.

Then I've built and run the docker. But when I'm calling `curl http://192.168.59.103:8080` the server is not responding. `Failed to connect to 192.168.59.103 port 8080: Connection refused`. To test docker configuration I took a server code from `google/dart-hello` and all is working fine. Do you know what might be wrong?

**Comment by emilniklas** [comment]
Have you changed the port in config/http.yaml from 1337 to 8080?

**Comment by marcinsydor** [comment]
Yes, I did.

**Comment by emilniklas** [comment]
And isnt docker supposed to proxy the server to port 80 on the external host?

Try starting the server and visit
http://192.168.59.103

**Comment by marcinsydor** [comment]
I found where was a problem. I had to change host to `host: '0.0.0.0'` in config/http.yaml
Yes, I'm testing it on http://192.168.59.103:8080/ address.
Thanks again :)

**Comment by emilniklas** [comment]
Great! Great! Good to know that it works on Docker
