### ISSUE TITLE
create database.mongodb.location as variable

### ISSUE THREAD

**Issue by SatWiz** [dart-bridge/framework#23]
Would like to create database.mongodb.location as variable to replace the hardcoded localhost in /packages/bridge/src/database/mongodb/mongo_database.dart

It seems the file is protected as it can not be edited? Maybe I doing at the wrong place, can you consider this as future in your next release?

**Comment by emilniklas** [comment]
Well, in the next release the entire database component will be rewritten, so...

What I'd recommend you do is to check out the `mongo_dart` package and reimplement the functionality in `bridge.database`. You can place the connection stuff in a Service Provider (check out the docs) and add it to `config/app.yaml`.

If it's too complicated to use a service provider you can do it in the constructor of the controller or anywhere you like

**Comment by SatWiz** [comment]
ok thanks, look forward for it :). Good practice meanwhile for me to figure out how rewrite a class in Dart is working.
