### ISSUE TITLE
Why is the Input Object mutable ?

### ISSUE THREAD

**Issue by adaojunior** [dart-bridge/framework#41]
```
class PagesController {
  index(Input input) {
    input.clear();
    input['key'] = 'value';
    ...
  }
}
```

Also, it would be nice to have a better api for the Input object instead of the Map's api.

```
input.get('name');
input.get('name','Adão'); // with a default value
input.has('name');
input.only(['name','age']);
input.toMap(); // if you really need it as a Map, maybe input.all() could to that instead
...
```

**Comment by emilniklas** [comment]
Some very good points being made here. It's a good thing we still have until the beta, or else this would have to be a 2.0 feature ✌🏻️

**Comment by emilniklas** [comment]
Just pushed some changes that addresses this:

Input now has a type argument `Input<T>` which translates to `Map<String, T>`. Input is immutable, and will copy itself on modifications.

All the methods you propose is added (with `toMap`), however with one exception: `only` returns an `Input<T>` so to get a map with only a few field, you would do `input.only(['field']).toMap()`.

There is also a getter `files`, which filters the Input into an `Input<UploadedFile>` which gives you IDE feedback on `input.files.get('file').saveTo(new File('target/file.txt');`
