### ISSUE TITLE
Because it is outside of the build environment

### ISSUE THREAD

**Issue by Hecatoncheir** [dart-bridge/framework#43]
Hi. When i make new project with new_bridge, and then use pub build i getting an error, like that:

```
Loading source assets... 
Loading libffi6_extension and unsafe_extension transformers... 
Building app... 
[Info from Dart2JS]:
Compiling app|web/main.dart...
Setup libffi6_extension.dylib.
Already installed binary 'compiled/X86_64/macos/libffi6_extension.dylib'
The setup successful.
Setup libunsafe_extension.dylib.
Already installed binary 'compiled/X86_64/macos/libunsafe_extension.dylib'
The setup successful.
[Error from Dart2JS]:
file:///Users/Vitaliy/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart: Exception: Cannot read file:///Users/Vitaliy/.pub-cache/hosted/pub.dartlang.org/libffi6_extension-0.0.6/lib/src/web/main.dart because it is outside of the build environment.
[Info from Dart2JS]:
Took 0:00:01.561045 to compile app|web/main.dart.
Build failed.
```

I can't use dart bridge build, because i need compile polymer, and use him transformers. 
Maybe it is due to a recent upgrade to a new mac distribution. I do not know, everything worked before. How do i can fix this?

**Comment by emilniklas** [comment]
I've run into this as well. Try removing the entire pub cache 

```
rm -rf ~/.pub-cache
```

And then running `pub upgrade` in the Bridge project

**Comment by emilniklas** [comment]
Oh and by the way, if you're using the dev branch of bridge in pubspec you need to lock it to the specific commit you're currently using, or else you will upgrade to new version of Bridge, with breaking changes

**Comment by emilniklas** [comment]
I've looked into this, and it seems `pub build` tries to load all the dependencies in pubspec even though they aren't used in the web/*.dart files. And since Bridge uses Trestle, which uses the sqlite_driver, which depends on native extension, and we cannot use native extension in dart2js, it blows up.

I will file an issue on pub and see what comes up!

**Comment by Hecatoncheir** [comment]
Thank you, very much. `rm -rf ~/.pub-cache` and `pub upgrade` it's the first thing I tried to do, but it's not work. Really I hope that will be the result of.

**Comment by emilniklas** [comment]
As a side note, the regular `dart2js` works, so you can still manually run:

```
$ mkdir build && mkdir build/web
$ for f in web/**/*.dart; dart2js -m -o build/$f.js $f
```

**Comment by emilniklas** [comment]
The build command now runs `pub build`. However, due to this issue, JavaScript compilation is run manually. To ignore dart files in pub build, this has to be injected in `pubspec`:

``` yaml
# Temporary (https://github.com/dart-lang/pub/issues/1341)
transformers:
- $dart2js:
    $exclude: web/**.dart
```
