### ISSUE TITLE
Tutorials

### ISSUE THREAD

**Issue by John0x** [dart-bridge/framework#58]
Hey, are there any good tutorials out there for dart-bridge?
The official documentation doesn't have any real tutorials and there are still parts missing in it.

**Comment by emilniklas** [comment]
Hello, @John0x. First of all, I think it's great that you're interested in Bridge.

I'm sorry to inform you that this project is going to be discontinued shortly.

Here's the reason: https://medium.com/@emilniklas/the-bridge-framework-is-being-discontinued-5c3e5c5ad8cc#.yoqo3ajyo

Visit https://github.com/emilniklas/embla for more information about the project that will replace Bridge.
